Repository qdrvm/kagome, pull requests merged in 2019-04, with the labels that each got.

#58 Update README.md
  README.md
Labels: small

#72 Change expected::Result to outcome::result in hexutil and related places
  core/common/blob.cpp
  core/common/blob.hpp
  core/common/buffer.cpp
  core/common/buffer.hpp
  core/common/hexutil.cpp
  core/common/hexutil.hpp
  core/libp2p/multi/multiaddress.cpp
  core/libp2p/multi/multiaddress.hpp
  core/libp2p/multi/multibase_codec.hpp
  core/libp2p/multi/multibase_codec/CMakeLists.txt
  core/libp2p/multi/multibase_codec/codecs/base16.cpp
  core/libp2p/multi/multibase_codec/codecs/base16.hpp
  core/libp2p/multi/multibase_codec/codecs/base58.cpp
  core/libp2p/multi/multibase_codec/codecs/base58.hpp
  core/libp2p/multi/multibase_codec/codecs/base64.cpp
  core/libp2p/multi/multibase_codec/codecs/base64.hpp
  core/libp2p/multi/multibase_codec/codecs/base_error.cpp
  core/libp2p/multi/multibase_codec/codecs/base_error.hpp
  core/libp2p/multi/multibase_codec/multibase_codec_impl.cpp
  core/libp2p/multi/multibase_codec/multibase_codec_impl.hpp
  core/libp2p/multi/multihash.cpp
  core/libp2p/multi/multihash.hpp
  test/core/common/blob_test.cpp
  test/core/common/buffer_test.cpp
  test/core/common/hexutil_test.cpp
  test/core/libp2p/multi/multiaddress_test.cpp
  test/core/libp2p/multi/multibase_codec_test.cpp
  test/core/libp2p/multi/multihash_test.cpp
  test/core/libp2p/peer/peer_id_test.cpp
  test/core/libp2p/peer/peer_info_test.cpp
Labels: enhancement

#87 LevelDB
  cmake/dependencies.cmake
  core/CMakeLists.txt
  core/extensions/impl/storage_extension.cpp
  core/libp2p/crypto/random/impl/std_generator.cpp
  core/libp2p/multi/converters/tcp_converter.cpp
  core/libp2p/multi/multibase_codec.hpp
  core/libp2p/multi/multibase_codec/multibase_codec_impl.cpp
  core/libp2p/multi/multibase_codec/multibase_codec_impl.hpp
  core/scale/collection.hpp
  core/scale/util.hpp
  core/scale/variant.hpp
  core/storage/CMakeLists.txt
  core/storage/buffer_map.hpp
  core/storage/face/generic_map.hpp
  core/storage/face/iterable_map.hpp
  core/storage/face/map_cursor.hpp
  core/storage/face/persisted_map.hpp
  core/storage/face/readable_map.hpp
  core/storage/face/write_batch.hpp
  core/storage/face/writeable_map.hpp
  core/storage/keyvalue.hpp
  core/storage/leveldb/CMakeLists.txt
  core/storage/leveldb/leveldb.cpp
  core/storage/leveldb/leveldb.hpp
  core/storage/leveldb/leveldb_batch.cpp
  core/storage/leveldb/leveldb_batch.hpp
  core/storage/leveldb/leveldb_cursor.cpp
  core/storage/leveldb/leveldb_cursor.hpp
  core/storage/leveldb/leveldb_error.cpp
  core/storage/leveldb/leveldb_error.hpp
  core/storage/leveldb/leveldb_util.hpp
  core/storage/merkle/trie_db.hpp
  test/CMakeLists.txt
  test/core/CMakeLists.txt
  test/core/extensions/storage_extension_test.cpp
  test/core/libp2p/muxer/yamux/yamux_integration_test.cpp
  test/core/storage/CMakeLists.txt
  test/core/storage/leveldb/CMakeLists.txt
  test/core/storage/leveldb/leveldb_fs_test.cpp
  test/core/storage/leveldb/leveldb_integration_test.cpp
  test/core/storage/merkle/mock_trie_db.hpp
  test/deps/CMakeLists.txt
  test/testutil/CMakeLists.txt
  test/testutil/outcome.hpp
  test/testutil/storage/CMakeLists.txt
  test/testutil/storage/base_fs_test.cpp
  test/testutil/storage/base_fs_test.hpp
  test/testutil/storage/base_leveldb_test.cpp
  test/testutil/storage/base_leveldb_test.hpp
Labels: big

#92 [PRE-131] Fix types of BlockHeader fields
  core/primitives/block_header.cpp
  core/primitives/block_header.hpp
  core/primitives/impl/scale_codec_impl.cpp
  test/core/primitives/primitives_codec_test.cpp
Labels: small
