Repository qdrvm/kagome, pull requests merged in 2020-02, with the labels that each got.

#275 Fix insert bug in polkadot trie
  core/storage/trie/impl/polkadot_trie.cpp
  test/core/storage/trie/trie_db/trie_db_test.cpp
Labels: big

#274 Optimize MP utils
  core/common/mp_utils.cpp
  test/core/common/CMakeLists.txt
  test/core/common/mp_utils_test.cpp
Labels: small

#278 Refactor Storage Interfaces
  core/blockchain/impl/CMakeLists.txt
  core/blockchain/impl/block_tree_impl.cpp
  core/blockchain/impl/common.hpp
  core/blockchain/impl/key_value_block_header_repository.cpp
  core/blockchain/impl/key_value_block_header_repository.hpp
  core/blockchain/impl/key_value_block_storage.cpp
  core/blockchain/impl/key_value_block_storage.hpp
  core/blockchain/impl/storage_util.cpp
  core/blockchain/impl/storage_util.hpp
  core/blockchain/impl/types.cpp
  core/injector/application_injector.hpp
  core/storage/buffer_map.hpp
  core/storage/buffer_map_types.hpp
  core/storage/face/batchable.hpp
  core/storage/face/generic_map.hpp
  core/storage/face/generic_maps.hpp
  core/storage/face/generic_storage.hpp
  core/storage/face/iterable.hpp
  core/storage/face/readable.hpp
  core/storage/face/write_batch.hpp
  core/storage/face/writeable.hpp
  core/storage/in_memory/in_memory_storage.hpp
  core/storage/leveldb/leveldb.hpp
  core/storage/trie/impl/CMakeLists.txt
  core/storage/trie/impl/polkadot_trie.hpp
  core/storage/trie/impl/polkadot_trie_batch.hpp
  core/storage/trie/impl/polkadot_trie_db.cpp
  core/storage/trie/impl/polkadot_trie_db.hpp
  core/storage/trie/impl/polkadot_trie_db_backend.cpp
  core/storage/trie/impl/trie_db_backend_impl.cpp
  core/storage/trie/impl/trie_db_backend_impl.hpp
  core/storage/trie/trie_db.hpp
  core/storage/trie/trie_db_backend.hpp
  core/storage/trie/trie_db_reader.hpp
  test/core/blockchain/CMakeLists.txt
  test/core/blockchain/block_header_repository_test.cpp
  test/core/blockchain/block_storage_test.cpp
  test/core/blockchain/block_tree_test.cpp
  test/core/extensions/storage_extension_test.cpp
  test/core/runtime/CMakeLists.txt
  test/core/runtime/block_builder_api_test.cpp
  test/core/runtime/core_integration_test.cpp
  test/core/runtime/runtime_test.hpp
  test/core/runtime/storage_wasm_provider_test.cpp
  test/core/storage/trie/mock_trie_db.hpp
  test/core/storage/trie/trie_db/CMakeLists.txt
  test/core/storage/trie/trie_db/trie_batch_test.cpp
  test/core/storage/trie/trie_db/trie_db_backend_test.cpp
  test/core/storage/trie/trie_db/trie_db_test.cpp
  test/mock/core/storage/persistent_map_mock.hpp
  test/mock/core/storage/trie/trie_db_mock.hpp
Labels: enhancement, help wanted

#286 Threshold util
  core/consensus/babe/impl/CMakeLists.txt
  core/consensus/babe/impl/threshold_util.cpp
  core/consensus/babe/impl/threshold_util.hpp
  test/core/consensus/babe/CMakeLists.txt
  test/core/consensus/babe/threshold_util_test.cpp
Labels: small
