Repository qdrvm/kagome, pull requests merged in 2022-06, with the labels that each got.

#1216 Feature/set_memory_type_dynamically
  cmake/Hunter/config.cmake
  cmake/Hunter/init.cmake
  core/injector/application_injector.cpp
  core/network/impl/peer_manager_impl.cpp
  core/runtime/common/CMakeLists.txt
  core/runtime/common/module_repository_impl.cpp
  core/runtime/common/module_repository_impl.hpp
  core/runtime/common/runtime_instances_pool.cpp
  core/runtime/common/runtime_instances_pool.hpp
  core/runtime/wavm/CMakeLists.txt
  core/runtime/wavm/core_api_factory_impl.cpp
  core/runtime/wavm/core_api_factory_impl.hpp
  core/runtime/wavm/instance_environment_factory.cpp
  core/runtime/wavm/instance_environment_factory.hpp
  core/runtime/wavm/intrinsics/intrinsic_module.cpp
  core/runtime/wavm/intrinsics/intrinsic_module.hpp
  core/runtime/wavm/intrinsics/intrinsic_module_instance.cpp
  core/runtime/wavm/intrinsics/intrinsic_module_instance.hpp
  core/runtime/wavm/module.cpp
  core/runtime/wavm/module.hpp
  core/runtime/wavm/module_factory_impl.cpp
  core/runtime/wavm/module_factory_impl.hpp
  core/runtime/wavm/module_params.cpp
  core/runtime/wavm/module_params.hpp
  test/core/runtime/runtime_test_base.hpp
  test/core/runtime/small_lru_cache_test.cpp
  test/core/runtime/wavm/wasm_executor_test.cpp
  test/core/runtime/wavm/wasm_memory_test.cpp
  test/core/runtime/wavm/wavm_runtime_test.hpp
  test/external-project-test/CMakeLists.txt
  test/external-project-test/src/main.cpp
Labels: Networking

#1240 Fixed various issues
  core/api/service/child_state/impl/child_state_api_impl.cpp
  core/application/impl/app_configuration_impl.cpp
  core/application/impl/app_configuration_impl.hpp
  core/blockchain/impl/block_tree_impl.cpp
  core/blockchain/impl/cached_tree.cpp
  core/consensus/babe/impl/babe_impl.cpp
  core/consensus/babe/impl/block_executor_impl.cpp
  core/consensus/babe/impl/threshold_util.cpp
  core/consensus/grandpa/impl/voting_round_impl.cpp
  core/consensus/grandpa/structs.hpp
  core/host_api/impl/offchain_extension.cpp
  core/network/impl/rating_repository_impl.cpp
  core/network/impl/sync_protocol_observer_impl.cpp
  core/offchain/impl/http_request.cpp
  core/offchain/impl/http_request.hpp
  core/offchain/impl/offchain_worker_impl.cpp
  core/offchain/types.hpp
  core/primitives/inherent_data.hpp
  core/runtime/common/runtime_upgrade_tracker_impl.cpp
  core/telemetry/impl/service_impl.cpp
  core/transaction_pool/impl/transaction_pool_impl.cpp
Labels: Technical debt

#1254 Removed open files limit. Fixed storage size measurement.
  core/injector/application_injector.cpp
  core/metrics/impl/metrics_watcher.cpp
  core/metrics/impl/metrics_watcher.hpp
Labels: bug
